### ISSUE TITLE
Resolving the WakaTime Issue

### ISSUE THREAD

**Issue by athul** [DaveEveritt/DaveEveritt#1]
Hey David,
I'm really sorry for the Shi**y docs in the Readme, I truly am. I was a bit excited to open it and didn't expect a fast adoption for the same. I saw your readme while I searched for `waka-readme` in GitHub to find out how people are using it. 

Anyways back to the point. I made changes to readme with Better Instructions(I guess). I'll paste them here too to get you a up and running .

## Prep Work
1. You need to update the markdown file(.md) with 2 comments. You can refer [here](https://github.com/athul/waka-readme#update-your-readme) for updating it.
2. You'll need a Wakatime API Key. You can get that from your Wakatime Account Settings
    - You can refer [here](https://github.com/athul/waka-readme#new-to-wakatime),if you're new to Wakatime
3. **Optional** You'll need a GitHub API Token with `repo` scope from [here](https://github.com/settings/tokens) if you're running the action not in your Profile Repository
    - You can use [this](https://github.com/athul/waka-readme#other-repository-not-profile) example to work it out
4. You need to save the if the Wakatime API Key (and the GitHub API Token, if you need it) in the repository secrets. You can find that in the Settings of your Repository. Be sure to save those as the following.
    - Wakatime-api-key as `WAKATIME_API_KEY = <your wakatime API Key>`and
    - The GitHub Access Token as `GH_TOKEN=<your github access token>`
5. You can follow either of the Two Examples according to your needs to get started with. 
> I strongly suggest you to run the Action in your Profile Repo since you won't be needing a GitHub Access Token

This Action will run everyday at 00.00 UTC

For the Action Part, you can just paste this `yml` file as a workflow file. You can create a new workflow at https://github.com/DaveEveritt/daveeveritt/actions/new

```yml
name: Waka Readme

on:
  push:
    branches: [ master ]
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
```

This is what I use in my Profile Repo.

**I'm sorry for opening an Issue** like this and again sorry for the dumb docs there. Have a nice day
